### ISSUE TITLE
add KubeCon discount code to slides

### ISSUE THREAD

**Issue by chadmcrowell** [k8sAustin/meetup-planning#20]
add KubeCon discount code to slides for Aug 29th meetup

**Comment by chadmcrowell** [comment]
added to August meetup slides here: https://docs.google.com/presentation/d/13CAJEVTBHDsRXV3lN9zLn1zKJ5LkC-OU8MpwT-FUfkY/edit?usp=sharing

**Comment by chadmcrowell** [comment]
added to sept slides here: https://docs.google.com/presentation/d/1fEp7v1822WMyr8z8IEyynOAj6rJNy6pODQs9rGgShsE/edit?usp=sharing

**Comment by brito-rafa** [comment]
done
